### ISSUE TITLE
Dialers can request unencrypted protocols via multistream-select.

### ISSUE THREAD

**Issue by tullrich** [libp2p/js-libp2p-switch#239]
Not sure if this is an intentional design choice. Dialers can request any registered protocol during the first phase of the connection when the encrypted channel is being selected.

I was able to connect to other peers without encryption by replacing the call to cryptoDial() in dial.js with gotWarmedUpConn(conn).

It doesn't appear there is a way to disallow this on the listener end since the same array of protocols (containing both the crypto protocol and others) is used throughout. 

As a workaround, users could always manually wrap their stream with an encrypted one.

**Comment by diasdavid** [comment]
Thanks for the report @tullrich! This is a known "issue" but it just happens in js-libp2p, go-libp2p forces a set of protocol by rounds.

I'm happy to accept a PR to lock this down. I was hoping to get https://github.com/ipfs/notes/issues/209 and https://github.com/libp2p/js-libp2p-swarm/issues/24 but unfortunately, we still haven't found the time to tackle those endeavors.
