### ISSUE TITLE
A proposal regarding over-complicated connection API.

### ISSUE THREAD

**Issue by serzero2007** [libp2p/js-libp2p-switch#255]
For now Connection API is a ES6 class with a lot of methods, used inconsistently along the codebase. I have experimented for some time with a different ways how to change the design, and would like to share my findings.
1) Treat connections as a generic objects without defining a class. 
2) From the typescript point of view these objects should provide Duplex Stream interface and Peer Info interface (have properties peerInfo and a method getObservedAddrs). 
3) Creating new connection objects using factories and transformation functions.

#### Why this approach is interesting? Well, see:
1) Factory
```ts
function attachPeerInfo (stream: Duplex, peerInfo: PeerInfo): Connection {
  stream.peerInfo = peerInfo
  if (stream.observer) stream.observer(stream, peerInfo, 'new', 'peerInfo')
  return stream // Actually a connection
}
```
2) Attaching the observer to the connection, so that observer function is called for each message:
```ts
import { tap } from 'pull-tap'

export function observeDuplexStream (stream, observer) {
  stream.observer = observer

  // This will allow to easely get stream.peerInfo
  let _out = tap(msg => stream.observer(stream, stream.peerInfo, 'out', msg))
  let _in  = tap(msg => stream.observer(stream, stream.peerInfo, 'in',  msg))

  // Monkey-patching the underlying streams
  stream.source = pull(stream.source, _out)
  stream.sink   = pull(_in, stream.sink)

  return stream
}
```
That's all. There is no need to define a complex interaction on the data. Observer will see the peerInfo on the stream when it appears.
3) The proxy stream with an observer and a different peerInfo attached:
```ts
const { duplex } = require('pull-defer')

function createProxyConnection (swarm): Connection {
  let proxy = duplex()
  // Basically a mixins that define the connection behaviour
  observeDuplexStream(proxy, swarm.observer)
  attachPeerInfo(proxy, swarm.peerInfo)
  // it's created! 
  return proxy
}
``` 

What do you think?

**Comment by serzero2007** [comment]
Also this would allow to add any number of annotations. ES6 Symbols can be used to get rid of name collision problems.

**Comment by jacobheun** [comment]
There's definitely merit in evaluating the simplicity of the connection api. This proposal should be moved to the interface, https://github.com/libp2p/interface-connection, as there are a number of modules that depend on that api.
