### ISSUE TITLE
Temporarily remove branch protection per ipfs/aegir#225

### ISSUE THREAD

**Issue by jacobheun** [libp2p/js-libp2p-switch#257]
@diasdavid @VictorBjelkholm I went to do a release of this today but it looks like branch protection is still enabled. I do not have perms to change that, can we get it remove per ipfs/aegir#225 until that is resolved.

It looks like a prior tag 0.40.0 also had the issue as the package.json was never updated, so I will clean that up once this is resolved.

**Comment by VictorBjelkholm** [comment]
@jacobheun try again now

**Comment by jacobheun** [comment]
Works now, thanks!
