### ISSUE TITLE
this.peerBook undefined?

### ISSUE THREAD

**Issue by alanshaw** [libp2p/js-libp2p-switch#299]
I was looking through the code in `index.js` and noticed that the passed `peerBook` is assigned to `_peerBook` in the constructor, but in `hangUp` it references `this.peerBook`:

https://github.com/libp2p/js-libp2p-switch/blob/5b498a0999d8b48a978539d308697c0573c83c8f/src/index.js#L172

Should it be referencing `this._peerBook` instead?

**Comment by jacobheun** [comment]
Yes, it should be `this._peerBook`. While getPeerInfo is protecting the failure, it's causing us to potentially recreate a PeerInfo instance, rather than using an existing one, when hanging up on a multiaddr.
