### ISSUE TITLE
Switch allows dial itself

### ISSUE THREAD

**Issue by alanshaw** [libp2p/js-libp2p-switch#326]
Discovery modules can emit `PeerInfo` objects with multiaddrs that **do not** have the peer ID encapsulated.

A libp2p node's own peer info seems to have multiaddrs that **do** have the peer ID encapsulated.

It means that a libp2p node will attempt to dial itself because the following test will fail, when attempting to `decapsulate` `/ip4/127.0.0.1/tcp/4002` from the peer's own address `/ip4/127.0.0.1/tcp/4002/ipfs/QmebzNV1kSzLfaYpSZdShuiABNUxoKT1vJmCdxM2iWsM2j`:

https://github.com/libp2p/js-libp2p-switch/blob/828e685e79a918831a6dac0a868d0b209dd5874c/src/transport.js#L212-L220

refs https://github.com/libp2p/js-libp2p/issues/323

**Comment by alanshaw** [comment]
I could PR a temporary fix for this @jacobheun if you like while we wait for https://github.com/libp2p/js-libp2p/issues/323 ?

**Comment by jacobheun** [comment]
@alanshaw I think a temporary fix is sufficient for now. I have https://github.com/libp2p/js-libp2p/issues/323 on my list for this quarter as a part of https://github.com/libp2p/js-libp2p/issues/202

**Comment by alanshaw** [comment]
On it
