### ISSUE TITLE
Peer should warn user if it discovers itself and drop event

### ISSUE THREAD

**Issue by mkg20001** [libp2p/js-libp2p-switch#331]
Based on https://github.com/libp2p/js-libp2p-webrtc-star/issues/171 I'm guessing peers shouldn't discover themselves

It would be great if the switch could:
 - detect a transport discovering the own peer
 - drop that event
 - log a warning like "WARN: Discovery module $NAME caused this peer to discover itself. This is a bug and should be reported at $URL" (url could be read from package.json, as npmjs.com currently does)
   - warning should be shown just once. possibly also print a line to debug log everytime this happens so user knows how frequently this is occuring

**Comment by jacobheun** [comment]
The recent update to `js-libp2p` centralizes the discovery logic a bit better, so we should do a check there, https://github.com/libp2p/js-libp2p/blob/v0.25.0/src/index.js#L479, and prevent the `PeerBook.put()` and discovery emits.

I created an issue at js-libp2p, https://github.com/libp2p/js-libp2p/issues/356, to track this there. Closing this.
