### ISSUE TITLE
Stats - possible to get a NaN

### ISSUE THREAD

**Issue by kumavis** [libp2p/js-libp2p-switch#335]
if you trigger `_updateFrequency` and `timeDiff` is calculated to zero, `hz` will be `Infinity` and the `movingAverage` will become `NaN`.

I managed to trigger this in a local dht test swarm of 5 nodes with randomWalk enabled

**Comment by kumavis** [comment]
can trigger it consistently with just 2 nodes

**Comment by kumavis** [comment]
I guess it happens if you push in an event immediately after creating the stats object (on a sufficiently fast machine?)

**Comment by kumavis** [comment]
```js
const Stat = require('libp2p-switch/src/stats/stat')
const defaultOptions = {
  computeThrottleMaxQueueSize: 1000,
  computeThrottleTimeout: 2000,
  movingAverageIntervals: [
    60 * 1000, // 1 minute
    5 * 60 * 1000, // 5 minutes
    15 * 60 * 1000 // 15 minutes
  ],
  maxOldPeersRetention: 50
}

const initialCounters = [
  'dataReceived',
  'dataSent'
]

const s = new Stat(initialCounters, defaultOptions)
s.push('dataReceived', 1)
s.once('update', () => {
    const ma = s.movingAverages.dataReceived[60*1000].movingAverage()
    console.log(ma) // NaN <-------------- broken moving average
})
```

**Comment by kumavis** [comment]
```
➜ node -v
v10.15.3
```
```
➜ lscpu | grep 'Model name'
Model name:          Intel(R) Core(TM) i7-8705G CPU @ 3.10GHz
```

**Comment by kumavis** [comment]
surprised this wasn't caught sooner, message is being pushed in after creation here
https://github.com/libp2p/js-libp2p-switch/blob/aa86307adbd529e568421b0cd838c64c7036ffde/src/stats/index.js#L113-L118

**Comment by kumavis** [comment]
slightly less reproducible on the browser, but still happens

as a work around, I set the minimal delta ms to be 1, and the average eventually fixes itself

**Comment by jacobheun** [comment]
Avoiding the divide by 0 for `timeDiffMS` by setting the min to 1 seems like a reasonable fix to mitigate this.
